// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLV8VBk0WLG2z-lYn5dTNprLR-ef-lEW0',
    appId: '1:812118734173:android:d1944eae67f7c8d2ef64b4',
    messagingSenderId: '812118734173',
    projectId: 'bpasic1-firebase-msc',
    storageBucket: 'bpasic1-firebase-msc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7GAysu-qqTXNqQtORfH-UXduCtepotyg',
    appId: '1:812118734173:ios:91f71a3c8d6fb120ef64b4',
    messagingSenderId: '812118734173',
    projectId: 'bpasic1-firebase-msc',
    storageBucket: 'bpasic1-firebase-msc.appspot.com',
    iosBundleId: 'com.example.counselingFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvlO80B-uLSR1oVFdNncT6FlE2S6fGPAw',
    appId: '1:812118734173:web:537ab09dbffb5390ef64b4',
    messagingSenderId: '812118734173',
    projectId: 'bpasic1-firebase-msc',
    authDomain: 'bpasic1-firebase-msc.firebaseapp.com',
    storageBucket: 'bpasic1-firebase-msc.appspot.com',
  );
}
